### ISSUE TITLE
Please add "target" support along with existing "href" support on Buttons

### ISSUE THREAD

**Issue by luke-hagar-sp** [Brain-Bones/skeleton#114]
The Button component currently supports "href" which works very well, but not the target attribute to specify "_blank" for a new tab.
for me, this leads to issues with wrapping the button with "a" crashing any browser I try it on (I have absolutely no idea why) or the inner "a" value having a very small "hitbox" to click on.

My specific use case here is a chrome extension written in SvelteKit, I will poke around your source and see if I can contribute to a fix

```HTML
<Button
	background="bg-primary-500"
	class="grow"
	color="text-white"
	href={`vscode://DeepLinkingWorksFine`}
>
	Open in Visual Studio Code
</Button>
<Button
	background="bg-primary-500"
	class="grow"
	color="text-white"
	href={`/RouteLinksWorkFine`}
>
	Open Different SvelteKit Route
</Button>
<Button
	background="bg-primary-500"
	class="grow"
	color="text-white"
	href={`https://github.com/LukeHagar/ExternalLinksInNewTabsDoNotWork`}
    target="_blank"
>
	Open Site URL in New Tab
</Button>
```

**Comment by endigo9740** [comment]
Hi Luke, unfortunately I'm having trouble replicating your issue. The target attribute works for for me. To test I copied your code snippet straight into a local Skeleton project and all three worked without issue. In fact we even use buttons with the target attribute on the documentation site. Try the "view stylesheet example" button near the top of this page:
https://skeleton.brainandbonesllc.com/guides/styling

You can view the source for this here:
https://github.com/Brain-Bones/skeleton/blob/dev/src/routes/guides/styling.svelte#L37

You mention you're writing a Chrome Extension, so I'm not sure if there's anything notable about how those operate compared to a standard webpage. My guess is both would use Chrome's Blink rendering engine and produce similar results though.

FYI I did also testing clicking all over the button and no issue there. The entire button parent is the anchor, so there should be no click area issues:

![Screen Shot 2022-08-17 at 12 01 08 PM](https://user-images.githubusercontent.com/1509726/185199469-484f437a-af14-475f-be9d-3487b3af9c93.png)

Happy to keep this open in case others can replicate to help troubleshoot. My suggestion would be to see if you get similar results when you open in the page, rather than an extension. Then that can at least help narrow our focus.

**Comment by luke-hagar-sp** [comment]
Hey Endigo, 

I have no clue what I was doing wrong but it is now operating perfectly. 
I apologize for this confusion.

As an output of this could we include the target value and maybe any other props like it on the Button Properties section of the skeleton site?

https://skeleton.brainandbonesllc.com/components/buttons

**Comment by endigo9740** [comment]
Ha, happens to the best of us! There's that old coding meme of "It's NOT working, and I don't know why - or - it IS working, and I don't know why!" :)

I think you raise a good point and that our documentation is missing critical information - that being that several of the components, including Buttons, already support ALL attributes! However, there's too many to document. It would be a mile long!

We do this by using the `$$restProps` feature in Svelte. Essentially it's a catch all to pass through any attribute defined on the component definition. So every attribute you want is available on the button right now. Give it a try! Use your browser's inspect tools to view the final results of the rendered element to see all this in action.

Just keep in mind the button is multi-purpose and works as both a native `<button>` as well as an anchor `<a>`. It defaults to the former unless an href is provided, otherwise it's an anchor. You'll only want to use attributes that are appropriate to the underlying tag.

I'll make note of this as we should explain this on the component docs for sure! For now I'll go ahead and close the issue as it appears to be resolved.

**Comment by luke-hagar-sp** [comment]
Man, I love this component Library.....

**Comment by endigo9740** [comment]
Ha, yeah we've thought of everything! Except for all the things we haven't yet :)
