### ISSUE TITLE
List and ListItem issues with ARIA

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#140]
Safari seems to be the main culprit here:

The LHS menu of the docs site, none of the ListItems are available to tab navigation - Safari only.

Looking at the /routes/components/lists/ page, clicking an item and then trying to shift tab to go up the list does not work in Safari
![Kapture 2022-08-22 at 15 30 11](https://user-images.githubusercontent.com/52020637/185846565-03641a62-15a2-4c01-97d8-6fc4d1d29cea.gif)
On the same page - tabbing to a new item and then pressing space or enter does not highlight the ListItem in FF, Chrome, Safari due to elemItem being null - line 48 in ListItem.svelte

**Comment by niktek** [comment]
Pretty sure this is an issue with line 48 in ListItem.svelte and that it should be reversing the ternary operands to:
```parentTag === 'nav' ? elemItem.click(): elemItem.querySelector('a').click();```

If parentTag is `nav` then the emitted tag is `a` and hence querySelector('a') will always fail as it looks for an anchor inside itself.  However, when parentTag is not nav, is there some benefit to trying to hit the anchor that may be nested in a slot - potential navigation ??  if not then the ternary can disappear and it can be just a elemItem.click()

This change makes highlighting via keyboard work across the board.

**Comment by niktek** [comment]
LHS menu issues are solved in Safari by turning on:
![image](https://user-images.githubusercontent.com/52020637/185865368-bd4f7828-099a-47cb-affa-bec74b55e879.png)

Why it worked for the components/lists/ page when this is off makes little sense.

**Comment by endigo9740** [comment]
Ugh, that's a frustrating default setting for Safari! Apply is using on the ball with user-centric defaults, so that's a big miss on their part. Hopefully folks that need this setting know about it!

Per the keypress event, you're correct, it should need to query within itself. It should just just trigger click on itself if it's part of a `nav` list set. I've dropped the favor in favor of a simple if statement. Good catch!

Just a single line fix so patched directly to dev branch.
