### ISSUE TITLE
Issues with Component Rework: List & List-Nav

### ISSUE THREAD

**Issue by Sarenor** [Brain-Bones/skeleton#257]
List & List-Nav:
The migration guide suggests:
```html
<nav class="list-nav">
    <ul>
        <li>
            <a href="/">
                <span class="badge bg-primary-500">💀</span>
                <span class="flex-auto">Skeleton</span>
            </a>
        </li>
		<!-- ... -->
    </ul>
</nav>
```
The css applied to list nav and the Skeleton Showcase omit the ``<li>`` element though, meaning you currently have to add
```css
.list-nav li {
	@apply flex items-center space-x-4 whitespace-nowrap;
	/* Padding */
	@apply px-4 py-3;
	/* Rounded */
	@apply rounded;
	/* Hover */
	@apply hover:bg-primary-500/10;

}
```
Yourself if you want to use ``<li>``-wrapped anchors in navigation.
After giving it more of a try, the ``<li>`` should probably just be removed from the documentation

**Comment by endigo9740** [comment]
@Sarenor You may have missed it, but I included some text under the Navigation List usage text that explain how we settled on the structure. It's due to accessibility (a11y) concerns:

![Screen Shot 2022-09-21 at 12 57 27 PM](https://user-images.githubusercontent.com/1509726/191577027-528f467b-6b1a-4ad0-98e3-d8be0a6dc242.png)

> Note the use of the ul tag, which is required to meet [accessibility guidelines](https://www.w3.org/WAI/tutorials/menus/structure/).

Per this linked page the guidelines show the following (NOTE: i've shorted this to one li/anchor):

```html
<ul>
    <li><a href="…">Home</a></li>
    …
</ul>
```

And then for Nav lists they show this:

```html
<nav>
    <ul>
        …
    </ul>
</nav>
```

So I've interpreted that as meaning they recommend the following structure for Nav lists:

`nav > ul > li > a`

Likewise, it's been a couple weeks, but I believe that [Axe](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US&utm_term=axe%20browser%20extension&utm_campaign=Search%20-%20axe%20DevTools%20-%20Checker&utm_source=adwords&utm_medium=ppc&hsa_src=g&hsa_ad=601366939661&hsa_tgt=kwd-942809056982&hsa_mt=e&hsa_ver=3&hsa_acc=7854167720&hsa_kw=axe%20browser%20extension&hsa_grp=142979637091&hsa_cam=17378411167&hsa_net=adwords&gclid=Cj0KCQjw7KqZBhCBARIsAI-fTKIZjDYjUESHJfBIkHi9DHMI28JTkgORzV38xz8kZYVpzcXOviI2L3UaAroOEALw_wcB) - the tool we use to test a11y - was also giving us an warning if we didn't use this structure.

It's very verbose, I agree, I'd prefer to drop the extra wrapping element if we could, but for now this appears to be the recommendation for a11y compliance.

If you can find info that states otherwise please share! I'd love to have a definitive answer on this!

**Comment by endigo9740** [comment]
I've updated the text slightly to this:

> While verbose, we do recommend you use all tags showng below as meets [accessibility guidelines](https://www.w3.org/WAI/tutorials/menus/structure/).

**Comment by endigo9740** [comment]
Also, unrelated, but I've included instruction for how we suggest handling TW element nav list highlight states. This aligns with how we handle this for our sidebar lists:

![Screen Shot 2022-09-21 at 1 26 09 PM](https://user-images.githubusercontent.com/1509726/191582165-d70d536e-3a75-4184-93f1-65022282456b.png)

**Comment by Sarenor** [comment]
You're right it works with 
```html
<nav>
    <ul>
        <li><a/><li>
        <!-- all of the links -->
    </ul>
</nav>
```
I apparently still had an issue with my CSS imports when I tested that because it looked absolutely horrible.

Still might want the skeleton showcase to also use <li> around the anchor tags then though.
Thanks for the response and sorry for needlessly taking your time!

**Comment by endigo9740** [comment]
Sorry I'm not sure what you're referring to with your bullet point. Where would that note go?
