### ISSUE TITLE
elements css produces The `aspect-square` class does not exist error

### ISSUE THREAD

**Issue by ainesophaur** [Brain-Bones/skeleton#272]
Switching to v0.41.48 produces the following error after going through the migration steps

```
@brainandbones/skeleton/styles/elements/buttons.css:46:2: The `aspect-square` class does not exist. If `aspect-square` is a custom class, make sure it is defined within a `@layer` directive.
```

I'm using skeleton inside a sveltekit project that uses vite and postcss

Here is my updated root layout svelte page

```
// src/routes/+layout.svelte
<script lang="ts">
    import '@brainandbones/skeleton/themes/theme-rocket.css';
    import '@brainandbones/skeleton/styles/all.css';
</script>
```

```
// src/app.postcss
html, body { @apply w-screen h-screen overflow-hidden ; }
```

```
// tailwinds.config.cjs
darkMode: 'class',
	content: [
		'./node_modules/@brainandbones/skeleton/**/*.{html,js,svelte,ts}',
		'./src/app.html',
		'./src/**/*.{svelte,ts}',
		'./src/routes/**/*.{svelte,js,ts}',
	],
        plugins : [
		require('@tailwindcss/typography'),
		require('@tailwindcss/forms'),
		require('@tailwindcss/aspect-ratio'),
		require('@tailwindcss/line-clamp'),
		require("@brainandbones/skeleton/tailwind/theme.cjs")
	]
```

**Comment by endigo9740** [comment]
I see you're using all.css which should do most of the heavy lifting when it comes to the CSS side of things. These may be silly questions since you mention you're migrating, but can you confirm the following:

1. You have Tailwind installed - seems so as the configuration is there and looks right.
2. Do you have a global stylesheet setup? Can you ensure you don't have the @tailwind directives inside this?

The Svelte Add feature we recommend during setup typically creates one for you in `/src/app.postcss` and they automatically insert the directives for you. However, `all.css` inserts the directives as well. So we just want to ensure we don't have them added twice. That cause cause some issues.

Also I haven't personally used the Aspect Ratio plugin from Tailwind. Unless you're using that for something specific, maybe try disabling it temporarily to see if that helps?

Let me know and we'll go from there! Likewise if this is something you can share a public repo or reproduce in a dedicated side project then please send that my way. It would be invaluable for debugging!

**Comment by ainesophaur** [comment]
1. Tailwinds ^3.1.8 is installed 
2. I do have a global style sheet (the `src/app.postcss` section above) and confirm that all the tailwinds directives are not present.

Disabling the aspect ratio plugin solved the issue. Let me know if you'd still like a sample repo to dig into it further, but I do not need the aspect ratio plugin for my project.

Thanks for the solution :)

**Comment by endigo9740** [comment]
Awesome, glad that helped!

That's very strange though. I'll dig into the plugin and see if I can figure why it might be causing an issue. I haven't used it personally but I was under the impression it just allowed for custom defined aspect ratios. Perhaps they modify the base aspect-X behavior in some fashion?

**Comment by ainesophaur** [comment]
FWIW, after filing the issue I came across a workaround by replacing the import of  'all.css' with a "patched" version

```css
/* all.patch.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind variants;

@layer components {
    .aspect-square {
        aspect-ratio: 1 / 1;
    }
}
```

```css
/* main layout svelte css */
import '@brainandbones/skeleton/themes/theme-rocket.css';
import '../all.patch.css'
import '@brainandbones/skeleton/styles/core.css';
import '@brainandbones/skeleton/styles/typography.css';
import '@brainandbones/skeleton/styles/forms.css'
import '@brainandbones/skeleton/styles/elements.css'
```

**Comment by endigo9740** [comment]
Hmm I'll have to think about this one. The point of `all.css` is it's supposed to import everything for you. Every single stylesheet we have available. This looks more like it's a replacement for the `tailwind.css` file:

https://github.com/Brain-Bones/skeleton/blob/dev/src/lib/styles/tailwind.css

I may need to split the Tailwind import out of the `all`. That way folks can sandwich their own custom Tailwind directive settings in the middle. Something like:

```
(theme.css)
(tailwind.css)
(custom tailwind directive stuff) <-- users can add this
(all.css)
(global stylesheet)
```

But again, I'll need to dive a bit deeper into why the Aspect plugin nukes the default aspect settings. Because there's a number of these. Square is the only one we utilize currently though.

**Comment by endigo9740** [comment]
@ainesophaur Finally had a chance to review this a bit more. Tailwind actually addresses this issue on their README here:
https://github.com/tailwindlabs/tailwindcss-aspect-ratio#compatibility-with-default-aspect-ratio-utilities

Essentially the plugin overrides the default values from the core library. However, if you follow the instructions here, and update your tailwind config, this should restore these. This means you could remove your work around above and use the `all.css` as is.

Would you mind terribly testing this out and reporting back? If it works for you, I'll update our docs to mention this. Which could help prevent this from tripping up a lot of other people in the future!

Please and thanks!

**Comment by ainesophaur** [comment]
@endigo9740 I was able to confirm the issue is resolved after following the instructions in the link. Without the fix, the aspect errors came back (just making sure the fix wasn't a false success)

**Comment by endigo9740** [comment]
Great, thanks for testing. I'll make sure to add a note about this in our docs.

**Comment by endigo9740** [comment]
Done:
https://github.com/Brain-Bones/skeleton/commit/be2ce638376cc7bfb6936f239eec70d794c5e8a1
