### ISSUE TITLE
Module '"@brainandbones/skeleton"' has no exported member 'dialogStore'

### ISSUE THREAD

**Issue by CodyOakes** [Brain-Bones/skeleton#276]
Getting this TS error when attempting to import "dialogStore" into a component to trigger a DialogConfirm:
Module '"@brainandbones/skeleton"' has no exported member 'dialogStore'

version: "@brainandbones/skeleton": "^0.41.48"

Noticed on line 42 of index.js in the skeleton source there is an import amongst all the exports:
import { dialogStore } from './utilities/Dialog/stores';

Enjoyed the package so far especially the most recent release, seems like it's moving in a great direction. Keep up the good work! Thanks!

**Comment by endigo9740** [comment]
Hey @CodyOakes, definitely seems we have a bug here. We utilize an `index.ts` file to define what resources should be available for the shorthand import method rather than including the full path inside the node_modules package directory. Here's a snippet of that:

![Screen Shot 2022-09-23 at 10 54 11 AM](https://user-images.githubusercontent.com/1509726/192002501-b5ceab2f-af74-4cbc-90ce-75bd95619225.png)

The `dialogStore` reference is there, but greyed out but the `toastStore` isn't. VS Code tells me this is because it's never used. But, well, of course it's not used. It's an export definition heh. The problem seems to be this is excluded when we actually build the package! Which isn't what we want.

I'm going to have to do a little research and figure out what's up here. In the meantime, you should able to work around this by importing from the full path. This would be:

```ts
import { dialogStore } from "@brainandbones/skeleton/utilities/Dialog/stores";
```

Sorry about that. If we can figure it out I may put out a quick hotpatch to help you and others. Let me know if the above solution works for you and thanks for the kind words!

**Comment by endigo9740** [comment]
@niktek any ideas on this one? Perhaps related to the new Svelte/Package issues you had mentioned prior?

**Comment by endigo9740** [comment]
@CodyOakes Ok, it just occurred to me what's up. We used `import` rather than `export`. Dumb mistake on my end :) I'll get a patch out later today!

**Comment by CodyOakes** [comment]
@endigo9740  Haha that's what I meant by "an import amongst all the exports". Thanks for the work around, and quick response! I'll watch for the patch.

**Comment by endigo9740** [comment]
Well shoot, you did! Seems I need a bit more coffee this morning :)

**Comment by endigo9740** [comment]
@CodyOakes The patch has been push. New version is `0.41.49`. Given how simple the change is I feel confident this will resolve your issue, so I'm going to close this ticket. But thanks for bringing this to our attention!

Let us know if you run into any other issues!
