### ISSUE TITLE
Disallow branches without proper prefixing

### ISSUE THREAD

**Issue by ryceg** [Brain-Bones/skeleton#308]
The use of a GitHub action will disallow non-standardized branch naming to ensure the code contribution guidelines are being followed implicitly.

**Comment by endigo9740** [comment]
The idea is interesting, but I have mixed feelings about this one. The branch naming is not a technical restriction but rather helps keep people doing PR reviews (like me) more organized. The reason this is helpful is at any given moment I have a NUMBER of branches available locally, typically due to PR reviews. It's helpful to be able bot tell these apart from one another:

![Screen Shot 2022-09-28 at 6 43 05 PM](https://user-images.githubusercontent.com/1509726/192907393-eea147e9-360e-45cf-8122-f0c1c96a1c26.png)

My concern is I don't want to put up a wall that prevents people from submitting contributing. Especially if it's due to a small typo or something like that. I've caught myself doing `feature/*` versus `feat/* a couple occasions. So, perhaps something we open up to the community for feedback on?

**Comment by endigo9740** [comment]
I've not seen this occur first hand. Do you have examples of what this looks like? As long as the response is clear to why this is rejected I may be more keen to accept it.

Things I would appreciate as contributor would be things like steps to resolve the issue. Your branch is X, but needs to be Y, here's the steps to resolve that.

Thoughts?

**Comment by endigo9740** [comment]
FYI I created a post on the Discord contributor channel and pinged a few folks to share their opinion here.

**Comment by ryceg** [comment]
[This article goes into detail about how to achieve it with Husky](https://www.devwithimagination.com/2020/04/13/git-commit-hooks-for-branch-naming-using-husky/). With a little more code you could give the user a command to copy + paste to amend their branch name. To avoid interrupting people that want to develop their own stuff, you could have it as a pre-pull hook that only triggers on the `dev` branch. Could also set up a pre-PR prettify hook to ensure consistency (but allow people to code in their own way up until that point of PR).

**Comment by ak4zh** [comment]
Feels like a bit of a barrier for first-time contributors.
We should keep barriers at a minimum so new contributors do not feel overwhelmed if they decide to send a pull request for say a typo or minor fixes.

My take on this:
Rules are great, but we are all learning and less strict rules help sometimes.
If this is my first ever pull request and it gets denied automatically I will feel more hostile to create a pull request next time. On the other hand, if it does not get denied outright I gain confidence to make more pull requests and contribute more.

Once it grows really big and starts receiving too many pull requests every day we can implement strict rules to make it easier to manage.

**Comment by endigo9740** [comment]
After thinking this over I don't believe we will move forward with this proposal. At least not yet. The branch naming conventions are merely guidelines, nothing more. I think between the addition of the [PR template](https://github.com/Brain-Bones/skeleton/issues/309) warning and general contribution guide improvements should be fine for now.

Once the project grows and we're getting regular PRs daily I'd like to revisit the idea though.

Thanks for the suggestion @ryceg!
