### ISSUE TITLE
Change menu origin automatically when there is not enough space

### ISSUE THREAD

**Issue by pikhosh** [Brain-Bones/skeleton#40]
For example, when the menu is very close to the bottom of the page and there is not enough space to display the content, the menu origin should change from "tl" to "bl".

Chakra UI:
![chrome_m5Ffy6298N](https://user-images.githubusercontent.com/73311467/181148910-08112773-dcd6-4eb9-9be0-1d77f258d0db.gif)

Skeleton:
![chrome_rGwzXX1A5z](https://user-images.githubusercontent.com/73311467/181149159-c50f4a79-f248-49f1-92c3-6308db5c26b3.gif)

**Comment by endigo9740** [comment]
Great suggestion and definitely something on my radar! I was planning a default `origin: 'auto`' setting, that would take into account the edges of the canvas. That way if your menu target place near a corner, it doesn't open off screen.

Thanks for linking the Chakra example as well. If you know of other examples feel free to link them here. I'd like to follow best practices when implementing something like this.

**Comment by endigo9740** [comment]
@pikhosh I've got an initial version of this working on the attached feature branch. Currently it supports the following:

* Default origin is now set to 'auto', which causes the menu to do it's best to stay on screen
* If auto, the menu position is auto-updated on window resize
* If auto, the menu position is auto-updated when the parent element is scrolled

Per that last bullet, it occurred to me that not every app will scroll the body element. Some apps (including the Skeleton docs) have a layout that scroll with a child element rather than the body (`<main>` in our case). So to handle this, I traverse up the DOM until I locate the first scrollable parent. Then listen to scroll events on that parent.

This does come with a "gotcha" that if the menu is embedded within multiple scrollable elements it may not act accordingly. However, I'm not sure that's a use case we want to cover right away. It may add a lot of unnecessary complexity.

Also, I'd love to grab a screen recording as a gif, as you did the original post. Would you mind sharing what tool you use to capture this please? I'll follow up result asap.

**Comment by pikhosh** [comment]
> @pikhosh I've got an initial version of this working on the attached feature branch. Currently it supports the following:
> 
> * Default origin is now set to 'auto', which causes the menu to do it's best to stay on screen
> * If auto, the menu position is auto-updated on window resize
> * If auto, the menu position is auto-updated when the parent element is scrolled
> 
> Per that last bullet, it occurred to me that not every app will scroll the body element. Some apps (including the Skeleton docs) have a layout scroll a child element instead (`<main>` in our case). So to handle this, I traverse up the DOM until I locate the first scrollable parent. Then listen to scroll events on that parent.
> 
> This does come with a "gotcha" that if the menu is embedded within multiple scrollable elements it may not act accordingly. However, I'm not sure that's a use case we want to cover right away. It may add a lot of unnecessary complexity.
> 
> Also, I'd love to grab a screen recording as a gif, as you did the original post. Would you mind sharing what tool you use to capture this please? I'll follow up with the result asap.

Thank you for your efforts! I'm happy to see that the project is progressing! 😄
I use [ShareX](https://github.com/ShareX/ShareX); It's also open source!

**Comment by endigo9740** [comment]
No problem! Unfortunately ShareX looks to be Windows only (I'm on a Mac!). I'll see if I can track down something similar. In the meantime I've use a free online tool to convert a quick video. Not the best quality, but hey it works!

![auto-menu](https://user-images.githubusercontent.com/1509726/182959178-51a2dad4-d5aa-4406-ab07-bad6899c0bbd.gif)

This only demonstrates vertical scroll, but horizontal should work as well. Likewise the window resize mention in my prior message!

**Comment by endigo9740** [comment]
@thomasbjespersen This is ready to be tested. I'd recommend testing under the following scenarios. Make sure you use either the default origin (nix the prop) or specify `origin="auto"`.

1. Place the menu in each of the four corners of the page. Ensure the menu attempts to open towards the center of the page. You can use a wrapping element + Tailwind to do this as follows:

```html
<div class="absolute top-4 left-4">(the-menu-here)</div>
```

2. Test that the menu updates when scrolling up/down and left/right. It should flip when it passes the horizontal and vertical medians (read: halfway points)

Also please note my comment above that describes the gotcha when embedding the Menu within multiple levels of scrollable elements. This is expect to fail.

Ping me if you need help with any of this!

**Comment by thomasbjespersen** [comment]
This is open to anyone able to test beforehand a final merge.

**Comment by endigo9740** [comment]
@pikhosh Feel free to give it a go. I'll aim to merge on Monday. Release TBD.

**Comment by pikhosh** [comment]
> @pikhosh Feel free to give it a go. I'll aim to merge on Monday. Release TBD.

It works well! I just wanted to ask how the default origin is selected? Because sometimes by setting `auto`, the origin switches between `tr` and `br` and sometimes `tl` and `bl`.

For example, after setting the Select menu origin to auto:
![ShareX_mTCo2vgVHQ](https://user-images.githubusercontent.com/73311467/183249246-97e2ba33-75f1-4671-8223-a0b28abe32eb.gif)
And after removing the disabled menu:
![chrome_39PCNSpeCv](https://user-images.githubusercontent.com/73311467/183249322-ff3f4f5e-93c0-4258-9eb0-455b451b30f7.gif)

**Comment by thomasbjespersen** [comment]
@endigo9740 - In the second screen that @pikhosh uploaded, it does seem to not update the origin until the page is scrolled. This is handled by setAutoOrigin I assume.

**Comment by thomasbjespersen** [comment]
@endigo9740 - There also seems to be some issues with spacing between the menu and the origin in some instances. Placing the current doc menu in upper left results in spacing differing between different origins. The same when scrolling up and down.


https://user-images.githubusercontent.com/52718757/183273316-658213d6-c566-4cbe-809e-5870830bb0f2.mov

[

https://user-images.githubusercontent.com/52718757/183273318-a94e52bc-b0e2-43d1-99e1-4a7dd4e454f9.mov

](url)

**Comment by endigo9740** [comment]
@pikhosh thank you for testing. Per your question, we have to have some kind of origin set when the page loads, so I'm running the same logic that determines updates the origin on init. Here's a quick visualization of how it works:

![Screen Shot 2022-08-08 at 10 58 30 AM](https://user-images.githubusercontent.com/1509726/183461290-6b0c85fc-a4d0-49be-987c-d41db96175df.png)

Imaging the screen split into four quadrants with the red line being the midpoint. The green blocks (buttons) represent the menu targets. Depending on which quadrant the target is in when the page loads (or post-scroll) the menu tries to open towards the middle.

This updates horizontally and vertically independently. So you have a target/menu low on the page, the menu might open upwards, but when you scroll and pass the midpoint of the screen, then it would flip downward since more space would be available.

Of course you can also override the auto-behavior and specific an origin. The menu will then be hardcoded to always use this, in cases the best origin can be predicted.

This is the best manner I could think of to handle this, however, I'm open to suggestions if you can think of something better.

**Comment by endigo9740** [comment]
FYI I'm trying to get us on a schedule to release new updates on Mondays going forward. I feel like what we have is a big improvement over what we had prior, so I'm going to go ahead and include current progress on this in a release today. I do welcome additional feedback on the items mentioned above though. If need be we can address anything else in subsequent updates.

We're going to have an influx of new eyeballs to the library soon, so I want to ensure things are in the best state possible by then. Feel free to follow up either here or on Discord (since I believe both of you are present there)
