### ISSUE TITLE
Example code and components preview should equivalent

### ISSUE THREAD

**Issue by falentio** [Brain-Bones/skeleton#405]
### Link to the Page

https://github.com/Brain-Bones/skeleton/blob/83d070653dd990ef56b41a0e5cbfba975f9771bf/src/routes/(inner)/components/steppers/%2Bpage.svelte#L144-L151

### Describe the Issue

I don't think it important, but it will easier to see how components look like when example code and preview are equivalent code

### Are you able to create a Pull Request with the fix?

Yes, I will work on it

**Comment by endigo9740** [comment]
@falentio We aim to keep the code snippets as simple as possible, so it's ease to parse how the basics work. If you ever want to view how our live examples are constructed I'd recommend viewing the documentation page source. There's a link for this near the top of each feature page.

https://www.skeleton.dev/components/steppers

This links here:
https://github.com/Brain-Bones/skeleton/blob/master/src/routes/(inner)/components/steppers/%2Bpage.svelte

That said, I do noticed the step `length` value is incorrectly showing a value of `5` instead of `2`. I'd gladly except a PR fixing that if you have a chance!
