### ISSUE TITLE
Prose code blocks have hard to read text in light mode (using primary-800)

### ISSUE THREAD

**Issue by jordharr** [Brain-Bones/skeleton#409]
### Current Behavior

No matter the theme, some text is very hard to read in code blocks in light mode

![image](https://user-images.githubusercontent.com/76656637/196905534-b3e965cf-9868-4eb4-9ee3-7b8bd996e351.png)
![image](https://user-images.githubusercontent.com/76656637/196905593-d753eb93-6bcb-430d-99fc-f22848408ab7.png)

### Steps To Reproduce

Create a ```<prose class="prose dark:prose-invert"></prose>``` and put a code block inside it, images attached in current behavior

**Comment by jordharr** [comment]
This can be fixed using a lighter --color-primary-800 - but ideally this would use a different color altogether?

**Comment by endigo9740** [comment]
@jordharr the Skeleton code blocks rely on Highlight.js to provide syntax highlighting. Highlight.js has it's own suite of themes that get applied to the code blocks to color the various portion of the code. This is fixed, and does not adjust based on light/dark mode. If fact if you test any of our preset themes on the doc site that none of the code blocks change. This is intentional as we want full contrast for code. We never allow theme colors to affect our code blocks - which is intentional.

We provide this warning near the bottom of the Usage section:
![Screen Shot 2022-10-20 at 11 14 20 AM](https://user-images.githubusercontent.com/1509726/197002733-20192678-5e2a-40a6-b342-288ad1d04d94.png)

For the Skeleton documentation site we actually cloned and modified one of the existing Highlight.js CSS themes to make it use Tailwind colors, but otherwise it's the exact same style regardless of theme and regardless of light/dark mode.

Also I'm not sure what a `<prose>` element is, that's not a valid HTML element:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element

Perhaps I'm missing something about your implementation here?

**Comment by jordharr** [comment]
> @jordharr the Skeleton code blocks rely on Highlight.js to provide syntax highlighting. Highlight.js has it's own suite of themes that get applied to the code blocks to color the various portion of the code. This is fixed, and does not adjust based on light/dark mode. If fact if you test any of our preset themes on the doc site that none of the code blocks change. This is intentional as we want full contrast for code. We never allow theme colors to affect our code blocks - which is intentional.
> 
> We provide this warning near the bottom of the Usage section:
> 
> ![Screen Shot 2022-10-20 at 11 14 20 AM](https://user-images.githubusercontent.com/1509726/197002733-20192678-5e2a-40a6-b342-288ad1d04d94.png)
> 
> For the Skeleton documentation site we actually cloned and modified one of the existing Highlight.js CSS themes to make it use Tailwind colors, but otherwise it's the exact same style regardless of theme and regardless of light/dark mode.
> 
> Also I'm not sure what a `<prose>` element is, that's not a valid HTML element:
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element
> 
> Perhaps I'm missing something about your implementation here?

https://tailwindcss.com/docs/typography-plugin

I'm rendering html from an external source which has code blocks in them using @tailwindcss/typography package - I'm on mobile so ill give a more thorough answer on implementation later - I may just target it directly with css instead.

**Comment by endigo9740** [comment]
Right, I've used the Typography plugin, but it provides a `.prose` class, not an HTML element. Are you saying that using this plugin is affecting the coloring for the code block? If so then per the doc you linked the solution would probably be this:

https://tailwindcss.com/docs/typography-plugin#undoing-typography-styles

Which is to apply `.not-prose` as a class provided to the code block. That would look something like this:

```html
<CodeBlock ... class="not-prose" />
```

The main take away is you do not want modifications occurring to your code blocks. They should remain static, or at least be tailed per light/dark modes. But the control is on your end, nothing for the components themselves. I suppose we could hardcode `.not-prose` into the component parent, but I'll have to think about that.

**Comment by jordharr** [comment]
Sorted this using css

```
pre:not(.unstyled):not(.code-block pre) {
    background: none;
}

code:not(.unstyled):not(.code-block code) {
    background-color: rgb(var(--color-surface-500));
    color: rgb(var(--color-primary-500));
    padding: 1rem;
}
```
