### ISSUE TITLE
Investigate setting up with workspaces

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#420]
### Current Behavior

From discord @fnf found issues with following the instructions from the docs site when he was using workspaces with yarn.  This is a gap in our testing.  But likely to rear its head as we approach mono repo and may affect us directly.

Be good to get this tested out with all package managers in both singular project and workspace setups to make sure we have correct info on docs pages and ultimately in the CLI installer.

**Comment by leranjun** [comment]
I've created a reproduction repo at https://github.com/leranjun/ashes if that's helpful :)

**Comment by endigo9740** [comment]
Copying my response from Discord...

@niktek @leranjun Yarn falls into the same category as PNPM in that if we want support for it, we need people around that can not only get it working upfront, but help maintain it over time. Unfortunately I'm the least qualified person  to help troubleshoot or diagnose issues wither either of these. The last thing I want to do is introduce support for either, and then issues keep cropping up that we can't solve. That helps no one. So please take that into consideration if you want support for these. 

I don't much care for NPM, but currently NPM is the only package manager we officially support. That will have to be our official stance for the time being. Which sucks obviously, because we want everyone to be able to use Skeleton.

**Comment by endigo9740** [comment]
With this is mind I've switched from a bug ticket to a feature request.

**Comment by endigo9740** [comment]
FYI I've deployed the following doc change to the dev branch. This will go live with the next release:
https://github.com/Brain-Bones/skeleton/issues/421

Given this, I'm going to go ahead and close out this ticket for now. When we get to the point we're ready to evaluate official support for Yarn/PNPM we can reference or reopen this ticket.

Thanks!

**Comment by leranjun** [comment]
Hey all - for future reference, the reason why it didn't work had nothing to do with yarn or workspaces specifically. It was because of this in `tailwind.config.cjs`:

```js
content: [
	'./src/**/*.{html,js,svelte,ts}',
	'./node_modules/@brainandbones/skeleton/**/*.{html,js,svelte,ts}'
],
```

Note that the relative import path is wrong. Changing it to

```js
content: [
	'./src/**/*.{html,js,svelte,ts}',
	'../../node_modules/@brainandbones/skeleton/**/*.{html,js,svelte,ts}'
],
```

in the repro repo fixed it for me. Took me too long to realise 🤦‍♂️
