### ISSUE TITLE
Issue using form

### ISSUE THREAD

**Issue by BoukeG** [Brain-Bones/skeleton#422]
### Current Behavior

Getting an error when trying to use forms.css:
The `bg-surface-200-700-token` class does not exist.

### Steps To Reproduce

# steps taken

## downloaded svelte:

```
npm create svelte@latest formbug
npm install
```

Used Barebone, TypeScript, pretty and vite

## Installed skeleton:

```
npm i @brainandbones/skeleton --save-dev
```

## Installed tailwindcss:

```
npx svelte-add@latest tailwindcss
npm install
```

## Changed files using:

[https://www.skeleton.dev/guides/tailwind]
[https://www.skeleton.dev/guides/styling]
[https://www.skeleton.dev/guides/themes]
[https://www.skeleton.dev/guides/frameworks/sveltekit]

Just the bares were changed to use Skeleton (works looking at the button), but not the form itself.

Then run:

```
npm run dev -- --open
```

Error:

```
formbug/node_modules/@brainandbones/skeleton/styles/forms.css:43:2: The `bg-surface-200-700-token` class does not exist. If `bg-surface-200-700-token` is a custom class, make sure it is defined within a `@layer` directive.
```

### Anything else?

I've reproduced the issue in a new project and uploaded to github:
https://github.com/BoukeG/formbug

**Comment by endigo9740** [comment]
@BoukeG Sorry for the delay on this. I've had a chance to pull down your repro and troubleshoot. There was two small issues, both related to your Stylesheet imports in `+layout.svelte`:

1. The theme always needs to be the first of the Skeleton stylesheet imports, since everything derives settings from this.
2. When you use `all.css` you do not need to manually import `forms.css`, given this is already included.

Here's the final result of these changes:

![Screen Shot 2022-10-24 at 2 28 32 PM](https://user-images.githubusercontent.com/1509726/197609759-01e8a142-cf40-414e-86a4-ee8dc2b35ffd.png)

![Screen Shot 2022-10-24 at 2 30 22 PM](https://user-images.githubusercontent.com/1509726/197609831-bd0cbef3-396c-46d3-9704-deaa8ddad9ff.png)
