### ISSUE TITLE
FileDropzone default text information is plural

### ISSUE THREAD

**Issue by dumtux** [Brain-Bones/skeleton#468]
### Current Behavior

`FileDropzone` is in single file mode by default.
But the information text is
> Drop files or click to select

This would be better
> Drop a file or click to select

And after enabling multiple file mode,
> Drop files or click to select

### Steps To Reproduce

```
<FileDropzone />
```

**Comment by endigo9740** [comment]
Good catch!

**Comment by leranjun** [comment]
https://github.com/Brain-Bones/skeleton/blob/df2e8cf469bb88ec8e159b58c55e1fe6aed18790/src/lib/components/FileDropzone/FileDropzone.svelte#L73-L76

I'm thinking that L74 could be changed to

```svelte
<div class="text-base font-bold">Drop {$$restProps.multiple ? 'files' : 'a file'} or click to select.</div>
```

although `$$restProps` seems to be [generally not recommended](https://svelte.dev/docs#template-syntax-attributes-and-props) due to optimisation issues. Could we consider just exporting `multiple` plainly instead?
