### ISSUE TITLE
Update alias to match new SK requirements

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#532]
### Current Behavior

https://kit.svelte.dev/docs/configuration#alias

This has moved from the vite config into kit's config and has changed how it functions - it now writes out the alias info to tsconfig.json and presumably notifies vite in some manner as well.

Keep in mind that this will have different impacts on typescript, vite (svg, css, json imports too) and Sveld imports, so it probably can't be just moved over into the new location without some testing on those areas.

**Comment by endigo9740** [comment]
@niktek I think this may be a case where the docs are out of date. I seemed to recall this purposely moving from the Svelte config to Vite not long ago. When testing I get the following errors:

![Screen Shot 2022-11-16 at 1 29 51 PM](https://user-images.githubusercontent.com/1509726/202276070-9090046b-9721-43be-9a41-65907d55f21d.png)

Feel free to confirm on your end though. A PR is welcome if you get it working, otherwise let's close this ticket please.

**Comment by endigo9740** [comment]
@niktek I've made the change, but this is odd. I could have swore these moved from Svelte -> Vite config not long ago. Hopefully it stays put this time!
