### ISSUE TITLE
Linting Pass

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#70]
As reported here, we're well overdue for a linting pass: https://github.com/Brain-Bones/skeleton/issues/67

I'd advise we handle this immediately following completion and merge of the a11y branch per this ticket: https://github.com/Brain-Bones/skeleton/issues/41

I'm anticipating this to be a lot of small issues (missing semicolon, etc.), so general process should go something like this

* Create the branch following [convention](https://skeleton.brainandbonesllc.com/docs/contributions) (ex: `bugfix/linting`)
* Run the Prettier lint command `npm run lint`
* Address each issue provided one-by-one
* Run automated test via Vitest to check for regressions `npm run test`
* Do a manual pass through the project to check for regressions

> Contact either @thomasbjespersen or myself if you have questions or need assistance

In the future we'll look to make this a regular process and/or automate with a CI/CD pipeline.

**Comment by niktek** [comment]
Have done a first pass on this, some notes: `npm run lint` only shows the filename of something wrong, you need to do 'npm run format' and then use the diff view to see what got changed.  And yes it is a lot of minor things like single/double quotes, extra commas, etc....

BUT - some of the more deliberate formatting in components, especially around large case statements for applying class strings, get stretched out vertically.  Also, it strips commented urls in <-- --> for some reason and I can see that they are handy reference urls that should not be removed.

Ultimately, it has to be script based, because it will be going to CI/CD at some point and there is no maintainer sanity to be had on vetting each commit for linting on top of things like code quality/functionality.  I'm happy to see if there is some more tweaking that can be done on the rules, but I dare say the defaults are pretty sane from the svelte linting settings that seem to be there.

**Comment by endigo9740** [comment]
Ok, sounds like the current config is not working as expected. We definitely don't want to strip out URL comments as those typically contain useful references or documentation. In that case, leave this one to me. I'll look to adjust the the config and then we'll go from there. Thanks for taking a look though!

**Comment by niktek** [comment]
Using the following as .prettierrc

{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 140,
	"htmlWhitespaceSensitivity": "ignore",
	"svelteSortOrder": "options-styles-scripts-markup",
	"svelteStrictMode": false,
	"svelteBracketNewLine": false,
	"svelteAllowShorthand": true,
	"svelteIndentScriptAndStyle": true
}

Comments aren't being stripped, but they are being moved to below the main `<script>` tag (well most of them anyways), this is most noticeable on ConicGradient.  And it likes `<script lang='postcss'>` at the top too.

Adjusting the printWidth to 140 stopped a few line wraps on `let class = 'long class string'` - but I can't confirm on a laptop right now if that makes side scrolling a thing. Not really a big deal either way.

It's really only, Button, Avatar, Menu, Toast, Tooltip and some of the source props for tables in data-tables, drawers, lists, menus, paginators that could do with a judicial `// prettier-ignore` to preserve some chunks.  Much less than I thought.

It has made the docs pages source a lot easier for spell checking due to the column wrap. Have done a visual check on the served docs pages and no rendering issues on that side either.

Definitely will wait till A11y stuff is done, but this is looking nice and straight forward now.

**Comment by endigo9740** [comment]
This is great! These changes will be far reaching so I'd like give this a once-over as well before we implement, but I'll definitely use your config as the baseline.

I'd be surprised if there's no a way to keep comments at the top of the file. Perhaps they need to be formatted multi-line?

```
/* 
 * Example Comment
*/
```

Line wrapping does help readability in most cases. We'll aim to modify the code and accommodate and meet the requirements we settle on (140, etc), then opt for the prettier-ignore as sparingly as possible.

Excited to check it out though!
