### ISSUE TITLE
Adding chore type to contrib and package updates

### ISSUE THREAD

**Issue by niktek** [Brain-Bones/skeleton#92]
Can we add a convention of using branches named chore/* for things like update of packages/linting/etc ?

Also, just want to flag that there are same major semver updates available to packages like the eslint and svelte eslint plugins that could have ramifications for the options available to us on https://github.com/Brain-Bones/skeleton/issues/70

Although I've done a `pnpm upgrade` and it all runs fine - I just want to check in with regards to how `npm update --save` is meant to work, because it doesn't upgrade svelte-kit to .405 or the adaptors to their latest versions either.

**Comment by endigo9740** [comment]
> Can we add a convention of using branches named chore/* for things like update of packages/linting/etc ?

Sounds like an excellent suggestion. We'll just need to update the contribution guidelines.

> Also, just want to flag that there are same major semver updates available to packages like the eslint and svelte eslint plugins that could have ramifications for the options available to us on https://github.com/Brain-Bones/skeleton/issues/70

I like to update dependencies periodically, but given there's always a chance of introducing breaking issues (because who uses semantic versioning these days, right?! heh) I tend to be a bit more conservative doing so. I'd say let's get the a11y update out the door then this can come after. One big change at a time!

> Although I've done a pnpm upgrade and it all runs fine - I just want to check in with regards to how npm update --save is meant to work, because it doesn't upgrade svelte-kit to .405 or the adaptors to their latest versions either.

AFAIK, `npm update` simply only works for minor/patch versions off top of my head. Updating is one of those things I've done a million times, but always somehow forget the specific between each go heh. Again, I'd say we revisit this soon.

**Comment by endigo9740** [comment]
Note the `chore/*` branch convention has been documented on the contributor guide. This will go live with the next deployment to the doc site!
