### ISSUE TITLE
Introduce new dev branch

### ISSUE THREAD

**Issue by endigo9740** [Brain-Bones/skeleton#97]
Per @niktek's suggestion, we need a branch between master and feature branches. This will allow hotpatching on master if we need it. We start simple and build up. Something like:

* `master` - as is, we'll build/package on update. Manual for now, automated later with CI/CD.
* `dev` (or staging) - we introduce this as the proceeding branch. I don't think we need both yet.

General idea is `dev` will serve as our merge target. All PRs, etc target this. Updates from `dev` are merged into `master` when we're ready to deploy to production. We won't get any more complex than this until we need to.

This will come with updated guidance on the README and Contribution guidelines.

I welcome feedback on this, but expect it to appear tomorrow (US/CST time)

**Comment by niktek** [comment]
I know these are arbitrary names and opinionated, but my 2 cents (Dollarydoos !).

`master` never made sense.  We literally use the `branch` command all the time and branches come off a `trunk`
We develop in our feature branches, but then attempt to merge multiple features into the `staging` area.

So my vote is for `trunk` and `staging` with all feature branches to originate from `staging` and `staging` being the only one that merges to `trunk` to be tagged as a release.

**Comment by endigo9740** [comment]
Ha, <3 Dollarydoos.

Sounds like you've used Subversion in the past?
http://guides.beanstalkapp.com/version-control/branching-best-practices.html

I may be showing revealing some ignorance on my end but this is the first I've heard of this paradigm! Makes the UX part of my brain start throwing some red flags on whether casual contributors will understand this.

As with many things in Skeleton, my inspiration here is Mantine:
https://mantine.dev/pages/contributing/
https://github.com/mantinedev/mantine/branches

Also I'm lazy, so typing `dev` is shorter :)

**Comment by niktek** [comment]
Heh, try CVS and then svn *shudder*

Nah, mainly from Github/Gitlab Flow paradigms:
https://www.gitkraken.com/learn/git/best-practices/git-branch-strategy
https://www.flagship.io/git-branching-strategies/

I do like having that safety net of merging back into staging before some CI/CD shoots it straight out to S3/GitHub Pages.  Our current situation right now seems like a good example - we have docs with A11y content updates, but also a mass rename of all docs pages due to SK.next.409 and the actual Skeleton lib updates that affect the doc functionality in two separate feature branches, but if we were to merge them to trunk before we release the actual package to npm, that wouldn't be cool.  And considering that the testing covers looking at the same pages, it would be a waste of time to do it once for each feature branch to verify when it could be all merged to staging for a final single look over before releasing it in tandem with the npm package.

But then again, we don't have CI/CD yet, so keeping it as simple as possible is fine by me too!

**Comment by endigo9740** [comment]
That's interesting. Yeah I think as we continue to grow things will evolve more and change. Given the limited staff and resources we're probably best to go with the simplest option. So we'll use the dev branch as mentioned in the OP. But I would like to read more into this going forward. Thanks for sharing Nik!

**Comment by endigo9740** [comment]
The branch is live and includes various updates to the documentation. This includes details for targeting the `dev` branch for all PRs going forward. I'll echo this info on the Discord as well.
